stableVersion: 2.6.0.Final
developmentVersion: 2.7.0-SNAPSHOT
jdkJavadocsBase: http://docs.oracle.com/javase/8/docs/api
profiles:
  development:
    showBuildStatus: false
  production:
    base_url: http://www.togglz.org/
    google_analytics:
      account: UA-7295879-8
    showBuildStatus: true
