stableVersion: 1.1.1.Final
previewVersion: 2.0.0.Beta1
developmentVersion: 2.0.0-SNAPSHOT
jdkJavadocsBase: http://docs.oracle.com/javase/7/docs/api
profiles:
  development:
    showBuildStatus: false
  production:
    base_url: http://www.togglz.org/
    google_analytics: UA-7295879-8
    showBuildStatus: true
    deploy:
      host: www.togglz.org
      path: /home/www/togglz.org/htdocs
