stableVersion: 1.0.0.Alpha6
developmentVersion: 1.0.0-SNAPSHOT
profiles:
  development:
  production:
    base_url: http://www.togglz.org/
    google_analytics: UA-7295879-8
    deploy:
      host: www.togglz.org
      path: /home/www/togglz.org/htdocs
